module OrganizationsHelper
  def ntee_filter_options
    options = [
      [ "All Filters", "" ],

      # --- IRS Activity Codes (From your original requirement) ---
      [ "B82 - Scholarships, Student Financial Aid Services, Awards (NTEE)", "B82" ],
      [ "040 - Scholarships (other) (IRS Activity Code)", "040" ],
      [ "561 - Gifts or Grants to individuals (other than scholarships) (IRS Activity Code)", "561" ],

      # --- A: Arts, Culture and Humanities (NTEE) ---
      [ "A01 - Alliance/Advocacy Organizations", "A01" ],
      [ "A02 - Management & Technical Assistance", "A02" ],
      [ "A03 - Professional Societies, Associations", "A03" ],
      [ "A05 - Research Institutes and/or Public Policy Analysis", "A05" ],
      [ "A11 - Single Organization Support", "A11" ],
      [ "A12 - Fund Raising and/or Fund Distribution", "A12" ],
      [ "A19 - Nonmonetary Support N.E.C.*", "A19" ],
      [ "A20 - Arts, Cultural Organizations - Multipurpose", "A20" ],
      [ "A23 - Cultural, Ethnic Awareness", "A23" ],
      [ "A24 - Folk Arts", "A24" ],
      [ "A25 - Arts Education", "A25" ],
      [ "A26 - Arts Council/Agency", "A26" ],
      [ "A27 - Community Celebrations", "A27" ],
      [ "A30 - Media, Communications Organizations", "A30" ],
      [ "A31 - Film, Video", "A31" ],
      [ "A32 - Television", "A32" ],
      [ "A33 - Printing, Publishing", "A33" ],
      [ "A34 - Radio", "A34" ],
      [ "A40 - Visual Arts Organizations", "A40" ],
      [ "A50 - Museum, Museum Activities", "A50" ],
      [ "A51 - Art Museums", "A51" ],
      [ "A52 - Children's Museums", "A52" ],
      [ "A53 - Folk Arts Museums", "A53" ],
      [ "A54 - History Museums", "A54" ],
      [ "A56 - Natural History, Natural Science Museums", "A56" ],
      [ "A57 - Science and Technology Museums", "A57" ],
      [ "A60 - Performing Arts Organizations", "A60" ],
      [ "A61 - Performing Arts Centers", "A61" ],
      [ "A62 - Dance", "A62" ],
      [ "A63 - Ballet", "A63" ],
      [ "A65 - Theater", "A65" ],
      [ "A68 - Music", "A68" ],
      [ "A69 - Symphony Orchestras", "A69" ],
      [ "A6A - Opera", "A6A" ],
      [ "A6B - Singing, Choral", "A6B" ],
      [ "A6C - Music Groups, Bands, Ensembles", "A6C" ],
      [ "A6E - Performing Arts Schools", "A6E" ],
      [ "A70 - Humanities Organizations", "A70" ],
      [ "A80 - Historical Societies, Related Historical Activities", "A80" ],
      [ "A82 - Historical Societies & Historic Preservation", "A82" ],
      [ "A84 - Commemorative Events", "A84" ],
      [ "A90 - Arts Service Organizations and Activities", "A90" ],
      [ "A99 - Arts, Culture, and Humanities N.E.C.", "A99" ],

      # --- B: Education (NTEE) ---
      [ "B01 - Alliance/Advocacy Organizations", "B01" ],
      [ "B02 - Management & Technical Assistance", "B02" ],
      [ "B03 - Professional Societies, Associations", "B03" ],
      [ "B05 - Research Institutes and/or Public Policy Analysis", "B05" ],
      [ "B11 - Single Organization Support", "B11" ],
      [ "B12 - Fund Raising and/or Fund Distribution", "B12" ],
      [ "B19 - Nonmonetary Support N.E.C.", "B19" ],
      [ "B20 - Elementary, Secondary Education, K - 12", "B20" ],
      [ "B21 - Kindergarten, Preschool, Nursery School, Early Admissions", "B21" ],
      [ "B24 - Primary, Elementary Schools", "B24" ],
      [ "B25 - Secondary, High School", "B25" ],
      [ "B28 - Specialized Education Institutions", "B28" ],
      [ "B30 - Vocational, Technical Schools", "B30" ],
      [ "B40 - Higher Education Institutions", "B40" ],
      [ "B41 - Community or Junior Colleges", "B41" ],
      [ "B42 - Undergraduate College (4-year)", "B42" ],
      [ "B43 - University or Technological Institute", "B43" ],
      [ "B50 - Graduate, Professional Schools (Separate Entities)", "B50" ],
      [ "B60 - Adult, Continuing Education", "B60" ],
      [ "B70 - Libraries", "B70" ],
      [ "B80 - Student Services, Organizations of Students", "B80" ],
      [ "B82 - Scholarships, Student Financial Aid Services, Awards", "B82" ],
      [ "B83 - Student Sororities, Fraternities", "B83" ],
      [ "B84 - Alumni Associations", "B84" ],
      [ "B90 - Educational Services and Schools - Other", "B90" ],
      [ "B92 - Remedial Reading, Reading Encouragement", "B92" ],
      [ "B94 - Parent/Teacher Group", "B94" ],
      [ "B99 - Education N.E.C.", "B99" ],

      # --- C: Environment (NTEE) ---
      [ "C01 - Alliance/Advocacy Organizations", "C01" ],
      [ "C02 - Management & Technical Assistance", "C02" ],
      [ "C03 - Professional Societies, Associations", "C03" ],
      [ "C05 - Research Institutes and/or Public Policy Analysis", "C05" ],
      [ "C11 - Single Organization Support", "C11" ],
      [ "C12 - Fund Raising and/or Fund Distribution", "C12" ],
      [ "C19 - Nonmonetary Support N.E.C.", "C19" ],
      [ "C20 - Pollution Abatement and Control Services", "C20" ],
      [ "C27 - Recycling Programs", "C27" ],
      [ "C30 - Natural Resources Conservation and Protection", "C30" ],
      [ "C32 - Water Resource, Wetlands Conservation and Management", "C32" ],
      [ "C34 - Land Resources Conservation", "C34" ],
      [ "C35 - Energy Resources Conservation and Development", "C35" ],
      [ "C36 - Forest Conservation", "C36" ],
      [ "C40 - Botanical, Horticultural, and Landscape Services", "C40" ],
      [ "C41 - Botanical Gardens, Arboreta and Botanical Organizations", "C41" ],
      [ "C42 - Garden Club, Horticultural Program", "C42" ],
      [ "C50 - Environmental Beautification and Aesthetics", "C50" ],
      [ "C60 - Environmental Education and Outdoor Survival Programs", "C60" ],
      [ "C99 - Environmental Quality, Protection, and Beautification N.E.C.", "C99" ],

      # --- D: Animal-Related (NTEE) ---
      [ "D01 - Alliance/Advocacy Organizations", "D01" ],
      [ "D02 - Management & Technical Assistance", "D02" ],
      [ "D03 - Professional Societies, Associations", "D03" ],
      [ "D05 - Research Institutes and/or Public Policy Analysis", "D05" ],
      [ "D11 - Single Organization Support", "D11" ],
      [ "D12 - Fund Raising and/or Fund Distribution", "D12" ],
      [ "D19 - Nonmonetary Support N.E.C.", "D19" ],
      [ "D20 - Animal Protection and Welfare", "D20" ],
      [ "D30 - Wildlife Preservation, Protection", "D30" ],
      [ "D31 - Protection of Endangered Species", "D31" ],
      [ "D32 - Bird Sanctuary, Preserve", "D32" ],
      [ "D33 - Fisheries Resources", "D33" ],
      [ "D34 - Wildlife Sanctuary, Refuge", "D34" ],
      [ "D40 - Veterinary Services", "D40" ],
      [ "D50 - Zoo, Zoological Society", "D50" ],
      [ "D60 - Other Services - Specialty Animals", "D60" ],
      [ "D61 - Animal Training, Behavior", "D61" ],
      [ "D99 - Animal-Related N.E.C.", "D99" ],

      # --- E: Health Care (NTEE) ---
      [ "E01 - Alliance/Advocacy Organizations", "E01" ],
      [ "E02 - Management & Technical Assistance", "E02" ],
      [ "E03 - Professional Societies, Associations", "E03" ],
      [ "E05 - Research Institutes and/or Public Policy Analysis", "E05" ],
      [ "E11 - Single Organization Support", "E11" ],
      [ "E12 - Fund Raising and/or Fund Distribution", "E12" ],
      [ "E19 - Nonmonetary Support N.E.C.", "E19" ],
      [ "E20 - Hospitals and Related Primary Medical Care Facilities", "E20" ],
      [ "E21 - Community Health Systems", "E21" ],
      [ "E22 - Hospital, General", "E22" ],
      [ "E24 - Hospital, Specialty", "E24" ],
      [ "E30 - Health Treatment Facilities, Primarily Outpatient", "E30" ],
      [ "E31 - Group Health Practice (Health Maintenance Organizations)", "E31" ],
      [ "E32 - Ambulatory Health Center, Community Clinic", "E32" ],
      [ "E40 - Reproductive Health Care Facilities and Allied Services", "E40" ],
      [ "E42 - Family Planning Centers", "E42" ],
      [ "E50 - Rehabilitative Medical Services", "E50" ],
      [ "E60 - Health Support Services", "E60" ],
      [ "E61 - Blood Supply Related", "E61" ],
      [ "E62 - Ambulance, Emergency Medical Transport Services", "E62" ],
      [ "E65 - Organ and Tissue Banks", "E65" ],
      [ "E70 - Public Health Program (Includes General Health and Wellness Promotion Services)", "E70" ],
      [ "E80 - Health, General and Financing", "E80" ],
      [ "E86 - Patient Services - Entertainment, Recreation", "E86" ],
      [ "E90 - Nursing Services (General)", "E90" ],
      [ "E91 - Nursing, Convalescent Facilities", "E91" ],
      [ "E92 - Home Health Care", "E92" ],
      [ "E99 - Health General and Rehabilitative N.E.C.", "E99" ],

      # --- F: Mental Health & Crisis Intervention (NTEE) ---
      [ "F01 - Alliance/Advocacy Organizations", "F01" ],
      [ "F02 - Management & Technical Assistance", "F02" ],
      [ "F03 - Professional Societies, Associations", "F03" ],
      [ "F05 - Research Institutes and/or Public Policy Analysis", "F05" ],
      [ "F11 - Single Organization Support", "F11" ],
      [ "F12 - Fund Raising and/or Fund Distribution", "F12" ],
      [ "F19 - Nonmonetary Support N.E.C.", "F19" ],
      [ "F20 - Alcohol, Drug and Substance Abuse, Dependency Prevention and Treatment", "F20" ],
      [ "F21 - Alcohol, Drug Abuse, Prevention Only", "F21" ],
      [ "F22 - Alcohol, Drug Abuse, Treatment Only", "F22" ],
      [ "F30 - Mental Health Treatment", "F30" ],
      [ "F31 - Psychiatric, Mental Health Hospital", "F31" ],
      [ "F32 - Community Mental Health Center", "F32" ],
      [ "F33 - Residential Mental Health Treatment", "F33" ],
      [ "F40 - Hot Line, Crisis Intervention Services", "F40" ],
      [ "F42 - Rape Victim Services", "F42" ],
      [ "F50 - Addictive Disorders N.E.C.", "F50" ],
      [ "F52 - Smoking Addiction", "F52" ],
      [ "F53 - Eating Disorder, Addiction", "F53" ],
      [ "F54 - Gambling Addiction", "F54" ],
      [ "F60 - Counseling, Support Groups", "F60" ],
      [ "F70 - Mental Health Disorders", "F70" ],
      [ "F80 - Mental Health Association", "F80" ],
      [ "F99 - Mental Health, Crisis Intervention N.E.C.", "F99" ],

      # --- G: Voluntary Health Associations & Medical Disciplines (NTEE) ---
      [ "G01 - Alliance/Advocacy Organizations", "G01" ],
      [ "G02 - Management & Technical Assistance", "G02" ],
      [ "G03 - Professional Societies, Associations", "G03" ],
      [ "G05 - Research Institutes and/or Public Policy Analysis", "G05" ],
      [ "G11 - Single Organization Support", "G11" ],
      [ "G12 - Fund Raising and/or Fund Distribution", "G12" ],
      [ "G19 - Support N.E.C.", "G19" ],
      [ "G20 - Birth Defects and Genetic Diseases", "G20" ],
      [ "G25 - Down Syndrome", "G25" ],
      [ "G30 - Cancer", "G30" ],
      [ "G32 - Breast Cancer", "G32" ],
      [ "G40 - Diseases of Specific Organs", "G40" ],
      [ "G41 - Eye Diseases, Blindness and Vision Impairments", "G41" ],
      [ "G42 - Ear and Throat Diseases", "G42" ],
      [ "G43 - Heart and Circulatory System Diseases, Disorders", "G43" ],
      [ "G44 - Kidney Disease", "G44" ],
      [ "G45 - Lung Disease", "G45" ],
      [ "G48 - Brain Disorders", "G48" ],
      [ "G50 - Nerve, Muscle and Bone Diseases", "G50" ],
      [ "G51 - Arthritis", "G51" ],
      [ "G54 - Epilepsy", "G54" ],
      [ "G60 - Allergy Related Diseases", "G60" ],
      [ "G61 - Asthma", "G61" ],
      [ "G70 - Digestive Diseases, Disorders", "G70" ],
      [ "G80 - Specifically Named Diseases", "G80" ],
      [ "G81 - AIDS", "G81" ],
      [ "G83 - Alzheimer's Disease", "G83" ],
      [ "G84 - Autism", "G84" ],
      [ "G90 - Medical Disciplines", "G90" ],
      [ "G92 - Biomedicine, Bioengineering", "G92" ],
      [ "G94 - Geriatrics", "G94" ],
      [ "G96 - Neurology, Neuroscience", "G96" ],
      [ "G98 - Pediatrics", "G98" ],
      [ "G99 - Voluntary Health Associations & Medical Disciplines N.E.C.", "G99" ],
      [ "G9B - Surgery Specialties", "G9B" ],

      # --- H: Medical Research (NTEE) ---
      [ "H01 - Alliance/Advocacy Organizations", "H01" ],
      [ "H02 - Management & Technical Assistance", "H02" ],
      [ "H03 - Professional Societies, Associations", "H03" ],
      [ "H05 - Research Institutes and/or Public Policy Analysis", "H05" ],
      [ "H11 - Single Organization Support", "H11" ],
      [ "H12 - Fund Raising and/or Fund Distribution", "H12" ],
      [ "H19 - Support N.E.C.", "H19" ],
      [ "H20 - Birth Defects, Genetic Diseases Research", "H20" ],
      [ "H25 - Down Syndrome Research", "H25" ],
      [ "H30 - Cancer Research", "H30" ],
      [ "H32 - Breast Cancer Research", "H32" ],
      [ "H40 - Diseases of Specific Organ Research", "H40" ],
      [ "H41 - Eye Diseases, Blindness & Vision Impairments Research", "H41" ],
      [ "H42 - Ear and Throat Research", "H42" ],
      [ "H43 - Heart, Circulatory Research", "H43" ],
      [ "H44 - Kidney Diseases Research", "H44" ],
      [ "H45 - Lung Diseases Research", "H45" ],
      [ "H48 - Brain Disorders Research", "H48" ],
      [ "H50 - Nerve, Muscle, Bone Diseases Research", "H50" ],
      [ "H51 - Arthritis Research", "H51" ],
      [ "H54 - Epilepsy Research", "H54" ],
      [ "H60 - Allergy Related Disease Research", "H60" ],
      [ "H61 - Asthma Research", "H61" ],
      [ "H70 - Digestive Disease, Disorder Research", "H70" ],
      [ "H80 - Specifically Named Diseases Research", "H80" ],
      [ "H81 - AIDS Research", "H81" ],
      [ "H83 - Alzheimer's Disease Research", "H83" ],
      [ "H84 - Autism Research", "H84" ],
      [ "H90 - Medical Disciplines Research", "H90" ],
      [ "H92 - Biomedicine, Bioengineering Research", "H92" ],
      [ "H94 - Geriatrics Research", "H94" ],
      [ "H96 - Neurology, Neuroscience Research", "H96" ],
      [ "H98 - Pediatrics Research", "H98" ],
      [ "H99 - Medical Research N.E.C.", "H99" ],
      [ "H9B - Surgical Specialties Research", "H9B" ],

      # --- I: Crime & Legal-Related (NTEE) ---
      [ "I01 - Alliance/Advocacy", "I01" ],
      [ "I02 - Management & Technical Assistance", "I02" ],
      [ "I03 - Professional Societies, Associations", "I03" ],
      [ "I05 - Research Institutes and Public Policy Analysis", "I05" ],
      [ "I11 - Single Organization Support", "I11" ],
      [ "I12 - Fund Raising and Fund Distribution", "I12" ],
      [ "I19 - Support N.E.C.", "I19" ],
      [ "I20 - Crime Prevention", "I20" ],
      [ "I21 - Delinquency Prevention", "I21" ],
      [ "I23 - Drunk Driving Related", "I23" ],
      [ "I30 - Correctional Facilities N.E.C.", "I30" ],
      [ "I31 - Half-Way House for Offenders, Ex-Offenders", "I31" ],
      [ "I40 - Rehabilitation Services for Offenders", "I40" ],
      [ "I43 - Inmate Support", "I43" ],
      [ "I44 - Prison Alternatives", "I44" ],
      [ "I50 - Administration of Justice, Courts", "I50" ],
      [ "I51 - Dispute Resolution, Mediation Services", "I51" ],
      [ "I60 - Law Enforcement", "I60" ],
      [ "I70 - Protection Against Abuse", "I70" ],
      [ "I71 - Spouse Abuse, Prevention", "I71" ],
      [ "I72 - Child Abuse, Prevention", "I72" ],
      [ "I73 - Sexual Abuse, Prevention", "I73" ],
      [ "I80 - Legal Services", "I80" ],
      [ "I83 - Public Interest Law", "I83" ],
      [ "I99 - Crime, Legal Related N.E.C.", "I99" ],

      # --- J: Employment (NTEE) ---
      [ "J01 - Alliance/Advocacy Organizations", "J01" ],
      [ "J02 - Management & Technical Assistance", "J02" ],
      [ "J03 - Professional Societies, Associations", "J03" ],
      [ "J05 - Research Institutes and/or Public Policy Analysis", "J05" ],
      [ "J11 - Single Organization Support", "J11" ],
      [ "J12 - Fund Raising and Fund Distribution", "J12" ],
      [ "J19 - Support N.E.C.", "J19" ],
      [ "J20 - Employment Procurement Assistance", "J20" ],
      [ "J21 - Vocational Counseling", "J21" ],
      [ "J22 - Job Training", "J22" ],
      [ "J30 - Vocational Rehabilitation", "J30" ],
      [ "J32 - Goodwill Industries", "J32" ],
      [ "J33 - Sheltered Employment", "J33" ],
      [ "J40 - Labor Unions", "J40" ],
      [ "J99 - Employment N.E.C.", "J99" ],

      # --- K: Food, Agriculture and Nutrition (NTEE) ---
      [ "K01 - Alliance/Advocacy", "K01" ],
      [ "K02 - Management & Technical Assistance", "K02" ],
      [ "K03 - Professional Societies & Associations", "K03" ],
      [ "K05 - Research Institutes and Public Policy Analysis", "K05" ],
      [ "K11 - Single Organization Support", "K11" ],
      [ "K12 - Fund Raising and Fund Distribution", "K12" ],
      [ "K19 - Support N.E.C.", "K19" ],
      [ "K20 - Agricultural Programs", "K20" ],
      [ "K25 - Farmland Preservation", "K25" ],
      [ "K26 - Animal Husbandry", "K26" ],
      [ "K28 - Farm Bureau, Grange", "K28" ],
      [ "K30 - Food Programs", "K30" ],
      [ "K31 - Food Banks, Pantries", "K31" ],
      [ "K34 - Congregate Meals", "K34" ],
      [ "K35 - Soup Kitchens", "K35" ],
      [ "K36 - Meals on Wheels", "K36" ],
      [ "K40 - Nutrition", "K40" ],
      [ "K50 - Home Economics", "K50" ],
      [ "K6A - Meat Markets", "K6A" ],
      [ "K6B - Confectionary and Nut Stores", "K6B" ],
      [ "K6C - Caterers", "K6C" ],
      [ "K6D - Mobile Food Services", "K6D" ],
      [ "K6E - Drinking Places (Alcoholic Beverages)", "K6E" ],
      [ "K6F - Snack and Nonalcoholic Beverage Bars", "K6F" ],
      [ "K90 - Limited-Service Restaurants", "K90" ],
      [ "K91 - Supermarkets and Other Grocery (except Convenience) Stores", "K91" ],
      [ "K92 - Convenience Stores", "K92" ],
      [ "K93 - Fruit and Vegetable Markets", "K93" ],
      [ "K94 - All Other Specialty Food Stores", "K94" ],
      [ "K95 - Food (Health) Supplement Stores", "K95" ],
      [ "K96 - Warehouse Clubs and Supercenters", "K96" ],
      [ "K97 - Food Service Contractors", "K97" ],
      [ "K98 - Full-Service Restaurants", "K98" ],
      [ "K99 - Food, Agriculture, and Nutrition N.E.C.", "K99" ],

      # --- L: Housing & Shelter (NTEE) ---
      [ "L01 - Alliance/Advocacy Organizations", "L01" ],
      [ "L02 - Management & Technical Assistance", "L02" ],
      [ "L03 - Professional Societies, Associations", "L03" ],
      [ "L05 - Research Institutes and Public Policy Analysis", "L05" ],
      [ "L11 - Single Organization Support", "L11" ],
      [ "L12 - Fund Raising and Fund Distribution", "L12" ],
      [ "L19 - Support N.E.C.", "L19" ],
      [ "L20 - Housing Development, Construction, Management", "L20" ],
      [ "L21 - Low-Income & Subsidized Rental Housing", "L21" ],
      [ "L22 - Senior Citizens' Housing/Retirement Communities", "L22" ],
      [ "L24 - Independent Housing for People with Disabilities", "L24" ],
      [ "L25 - Housing Rehabilitation", "L25" ],
      [ "L30 - Housing Search Assistance", "L30" ],
      [ "L40 - Temporary Housing", "L40" ],
      [ "L41 - Homeless Shelters", "L41" ],
      [ "L50 - Homeowners & Tenants Associations", "L50" ],
      [ "L80 - Housing Support", "L80" ],
      [ "L81 - Home Improvement and Repairs", "L81" ],
      [ "L82 - Housing Expense Reduction Support", "L82" ],
      [ "L99 - Housing, Shelter N.E.C.", "L99" ],

      # --- M: Public Safety, Disaster Preparedness & Relief (NTEE) ---
      [ "M01 - Alliance/Advocacy", "M01" ],
      [ "M02 - Management & Technical Assistance", "M02" ],
      [ "M03 - Professional Societies, Associations", "M03" ],
      [ "M05 - Research Institutes and Public Policy Analysis", "M05" ],
      [ "M11 - Single Organization Support", "M11" ],
      [ "M12 - Fund Raising and Fund Distribution", "M12" ],
      [ "M19 - Support N.E.C.", "M19" ],
      [ "M20 - Disaster Preparedness and Relief Services", "M20" ],
      [ "M23 - Search and Rescue Squads", "M23" ],
      [ "M24 - Fire Prevention", "M24" ],
      [ "M40 - Safety Education", "M40" ],
      [ "M41 - First Aid", "M41" ],
      [ "M42 - Automotive Safety", "M42" ],
      [ "M60 - Public Safety Benevolent Associations", "M60" ],
      [ "M99 - Public Safety. Disaster Preparedness & Relief N.E.C", "M99" ],

      # --- N: Recreation & Sports (NTEE) ---
      [ "N01 - Alliance/Advocacy", "N01" ],
      [ "N02 - Management & Technical Assistance", "N02" ],
      [ "N03 - Professional Societies, Associations", "N03" ],
      [ "N05 - Research Institutes and/or Public Policy Analysis", "N05" ],
      [ "N11 - Single Organization Support", "N11" ],
      [ "N12 - Fund Raising and Fund Distribution", "N12" ],
      [ "N19 - Support N.E.C.", "N19" ],
      [ "N20 - Camps", "N20" ],
      [ "N2A - RV (Recreation Vehicle) Parks and Campgrounds", "N2A" ],
      [ "N2B - Recreational and Vacation Camps (Except Campgrounds)", "N2B" ],
      [ "N30 - Physical Fitness and Community Recreational Facilities", "N30" ],
      [ "N31 - Community Recreational Centers", "N31" ],
      [ "N32 - Parks and Playgrounds", "N32" ],
      [ "N40 - Sports Associations & Training Facilities", "N40" ],
      [ "N50 - Recreational I Clubs", "N50" ],
      [ "N52 - Fairs", "N52" ],
      [ "N60 - Amateur Sports", "N60" ],
      [ "N61 - Fishing, Hunting", "N61" ],
      [ "N62 - Basketball", "N62" ],
      [ "N63 - Baseball, Softball", "N63" ],
      [ "N64 - Soccer", "N64" ],
      [ "N65 - Football", "N65" ],
      [ "N66 - Racquet Sports", "N66" ],
      [ "N67 - Swimming & Other Water Recreation", "N67" ],
      [ "N68 - Winter Sports", "N68" ],
      [ "N69 - Equestrian", "N69" ],
      [ "N6A - Golf", "N6A" ],
      [ "N70 - Amateur Sports Competitions", "N70" ],
      [ "N71 - Olympics", "N71" ],
      [ "N72 - Special Olympics", "N72" ],
      [ "N80 - Professional Athletic Leagues", "N80" ],
      [ "N99 - Recreation& Sports N.E.C.", "N99" ],

      # --- O: Youth Development (NTEE) ---
      [ "O01 - Alliance/Advocacy", "O01" ],
      [ "O02 - Management & Technical Assistance", "O02" ],
      [ "O03 - Professional Societies, Associations", "O03" ],
      [ "O05 - Research Institutes and Public Policy Analysis", "O05" ],
      [ "O11 - Single Organization Support", "O11" ],
      [ "O12 - Fund Raising and Fund Distribution", "O12" ],
      [ "O19 - Support N.E.C.", "O19" ],
      [ "O20 - Youth Centers, Clubs", "O20" ],
      [ "O21 - Boys Clubs", "O21" ],
      [ "O22 - Girls Clubs", "O22" ],
      [ "O23 - Boys and Girls Clubs", "O23" ],
      [ "O30 - Adult, Child Matching Programs", "O30" ],
      [ "O31 - Big Brothers, Big Sisters", "O31" ],
      [ "O40 - Scouting", "O40" ],
      [ "O41 - Boy Scouts of America", "O41" ],
      [ "O42 - Girl Scouts of the U.S.A.", "O42" ],
      [ "O43 - Camp Fire", "O43" ],
      [ "O50 - Youth Development Programs", "O50" ],
      [ "O51 - Youth Community Service Clubs", "O51" ],
      [ "O52 - Youth Development Agricultural", "O52" ],
      [ "O53 - Youth Development - Business", "O53" ],
      [ "O54 - Youth Development - Citizenship", "O54" ],
      [ "O55 - Youth Development Religious Leadership", "O55" ],
      [ "O99 - Youth Development N.E.C.", "O99" ],

      # --- P: Human Services (NTEE) ---
      [ "P01 - Alliance/Advocacy", "P01" ],
      [ "P02 - Management & Technical Assistance", "P02" ],
      [ "P03 - Professional Societies, Associations", "P03" ],
      [ "P05 - Research Institutes and Public Policy Analysis", "P05" ],
      [ "P11 - Single Organization Support", "P11" ],
      [ "P12 - Fund Raising and Fund Distribution", "P12" ],
      [ "P19 - Support N.E.C.", "P19" ],
      [ "P20 - Human Service Organizations", "P20" ],
      [ "P21 - American Red Cross", "P21" ],
      [ "P22 - Urban League", "P22" ],
      [ "P24 - Salvation Army", "P24" ],
      [ "P26 - Volunteers of America", "P26" ],
      [ "P27 - Young Men's or Women's Associations", "P27" ],
      [ "P28 - Neighborhood Centers", "P28" ],
      [ "P29 - Thrift Shops", "P29" ],
      [ "P30 - Children's, Youth Services", "P30" ],
      [ "P31 - Adoption", "P31" ],
      [ "P32 - Foster Care", "P32" ],
      [ "P33 - Child Day Care", "P33" ],
      [ "P40 - Family Services", "P40" ],
      [ "P42 - Single Parent Agencies", "P42" ],
      [ "P43 - Family Violence Shelters", "P43" ],
      [ "P44 - In-Home Assistance", "P44" ],
      [ "P45 - Family Services for Adolescent Parents", "P45" ],
      [ "P46 - Family Counseling", "P46" ],
      [ "P47 - Pregnancy Centers", "P47" ],
      [ "P50 - Personal Social Services", "P50" ],
      [ "P51 - Financial Counseling", "P51" ],
      [ "P52 - Transportation Assistance", "P52" ],
      [ "P58 - Gift Distribution", "P58" ],
      [ "P60 - Emergency Assistance", "P60" ],
      [ "P61 - Travelers' Aid", "P61" ],
      [ "P62 - Victims' Services", "P62" ],
      [ "P70 - Residential Care & Adult Day Programs", "P70" ],
      [ "P71 - Adult Day Care", "P71" ],
      [ "P73 - Group Homes", "P73" ],
      [ "P74 - Hospices", "P74" ],
      [ "P75 - Supportive Housing for Older Adults", "P75" ],
      [ "P80 - Centers to Support the Independence of Specific Populations", "P80" ],
      [ "P81 - Senior Centers", "P81" ],
      [ "P82 - Developmentally Disabled Centers", "P82" ],
      [ "P84 - Ethnic, Immigrant Centers", "P84" ],
      [ "P85 - Homeless Centers", "P85" ],
      [ "P86 - Blind/Visually Impaired Centers", "P86" ],
      [ "P87 - Deaf/Hearing Impaired Centers", "P87" ],
      [ "P88 - LGBT Centers", "P88" ],
      [ "P99 - Human Services N.E.C.", "P99" ],

      # --- Q: International, Foreign Affairs and National Security (NTEE) ---
      [ "Q01 - Alliance/Advocacy Organizations", "Q01" ],
      [ "Q02 - Management & Technical Assistance", "Q02" ],
      [ "Q03 - Professional Societies, Associations", "Q03" ],
      [ "Q05 - Research Institutes and Public Policy Analysis", "Q05" ],
      [ "Q11 - Single Organization Support", "Q11" ],
      [ "Q12 - Fund Raising and Fund Distribution", "Q12" ],
      [ "Q19 - Support N.E.C.", "Q19" ],
      [ "Q20 - Promotion of International Understanding", "Q20" ],
      [ "Q21 - International Cultural Exchange", "Q21" ],
      [ "Q22 - International Academic Exchange", "Q22" ],
      [ "Q23 - International Exchange, N.E.C.", "Q23" ],
      [ "Q30 - International Development", "Q30" ],
      [ "Q31 - International Agricultural Development", "Q31" ],
      [ "Q32 - International Economic Development", "Q32" ],
      [ "Q33 - International Relief", "Q33" ],
      [ "Q34 - International Educational Development", "Q34" ],
      [ "Q35 - International Democracy & Civil Society Development", "Q35" ],
      [ "Q36 - International Science & Technology Development", "Q36" ],
      [ "Q38 - International Environment, Population & Sustainability", "Q38" ],
      [ "Q39 - International Health Development", "Q39" ],
      [ "Q40 - International Peace and Security", "Q40" ],
      [ "Q41 - Arms Control, Peace", "Q41" ],
      [ "Q42 - United Nations Association", "Q42" ],
      [ "Q43 - National Security", "Q43" ],
      [ "Q50 - International Affairs, Foreign Policy, & Globalization", "Q50" ],
      [ "Q51 - International Economic & Trade Policy", "Q51" ],
      [ "Q70 - International Human Rights", "Q70" ],
      [ "Q71 - International Migration, Refugee Issues", "Q71" ],
      [ "Q99 - International, Foreign Affairs, and National Security N.E.C.", "Q99" ],

      # --- R: Civil Rights, Social Action, Advocacy (NTEE) ---
      [ "R01 - Alliance/Advocacy", "R01" ],
      [ "R02 - Management & Technical Assistance", "R02" ],
      [ "R03 - Professional Societies, Associations", "R03" ],
      [ "R05 - Research Institutes and Public Policy Analysis", "R05" ],
      [ "R11 - Single Organization Support", "R11" ],
      [ "R12 - Fund Raising and Fund Distribution", "R12" ],
      [ "R19 - Support N.E.C.", "R19" ],
      [ "R20 - Civil Rights", "R20" ],
      [ "R21 - Immigrant's Rights", "R21" ],
      [ "R22 - Minority Rights", "R22" ],
      [ "R23 - Disabled Persons' Rights", "R23" ],
      [ "R24 - Women's Rights", "R24" ],
      [ "R25 - Seniors' Rights", "R25" ],
      [ "R26 - Lesbian, Gay Rights", "R26" ],
      [ "R27 - Patient's Rights", "R27" ],
      [ "R28 - Children's Rights", "R28" ],
      [ "R29 - Employee & Workers Rights", "R29" ],
      [ "R30 - Intergroup, Race Relations", "R30" ],
      [ "R40 - Voter Education, Registration", "R40" ],
      [ "R60 - Civil Liberties", "R60" ],
      [ "R61 - Reproductive Rights", "R61" ],
      [ "R62 - Right to Life", "R62" ],
      [ "R63 - Censorship, Freedom of Speech and Press", "R63" ],
      [ "R65 - Freedom of Religion Issues", "R65" ],
      [ "R67 - Right to Die, Euthanasia", "R67" ],
      [ "R99 - Civil Rights, Social Action, Advocacy N.E.C.", "R99" ],

      # --- S: Community Improvement, Capacity Building (NTEE) ---
      [ "S01 - Alliance/Advocacy", "S01" ],
      [ "S02 - Management & Technical Assistance", "S02" ],
      [ "S03 - Professional Societies, Associations", "S03" ],
      [ "S05 - Research Institutes and Public Policy Analysis", "S05" ],
      [ "S11 - Single Organization Support", "S11" ],
      [ "S12 - Fund Raising and Fund Distribution", "S12" ],
      [ "S19 - Support N.E.C.", "S19" ],
      [ "S20 - Community, Neighborhood Development", "S20" ],
      [ "S21 - Community Coalitions", "S21" ],
      [ "S22 - Neighborhood, Block Associations", "S22" ],
      [ "S30 - Economic Development", "S30" ],
      [ "S31 - Urban, Community Economic Development", "S31" ],
      [ "S32 - Rural Economic Development", "S32" ],
      [ "S40 - Business and Industry", "S40" ],
      [ "S41 - Chambers of Commerce & Business Leagues", "S41" ],
      [ "S43 - Small Business Development", "S43" ],
      [ "S46 - Boards of Trade", "S46" ],
      [ "S47 - Real Estate Associations", "S47" ],
      [ "S50 - Nonprofit Management", "S50" ],
      [ "S80 - Community Service Clubs", "S80" ],
      [ "S81 - Women's Service Clubs", "S81" ],
      [ "S82 - Men's Service Clubs", "S82" ],
      [ "S99 - Community Improvement, Capacity Building N.E.C.", "S99" ],

      # --- T: Philanthropy, Voluntarism and Grantmaking Foundations (NTEE) ---
      [ "T01 - Alliance/Advocacy", "T01" ],
      [ "T02 - Management & Technical Assistance", "T02" ],
      [ "T03 - Professional Societies, Associations", "T03" ],
      [ "T05 - Research Institutes and Public Policy Analysis", "T05" ],
      [ "T11 - Single Organization Support", "T11" ],
      [ "T12 - Fund Raising and Fund Distribution", "T12" ],
      [ "T19 - Support N.E.C.", "T19" ],
      [ "T20 - Private Grantmaking Foundations", "T20" ],
      [ "T21 - Corporate Foundations", "T21" ],
      [ "T22 - Private Independent Foundations", "T22" ],
      [ "T23 - Private Operating Foundations", "T23" ],
      [ "T30 - Public Foundations", "T30" ],
      [ "T31 - Community Foundations", "T31" ],
      [ "T40 - Voluntarism Promotion", "T40" ],
      [ "T50 - Philanthropy, Charity, Voluntarism Promotion", "T50" ],
      [ "T70 - Federated Giving Programs", "T70" ],
      [ "T90 - Named Trusts N.E.C.", "T90" ],
      [ "T99 - Philanthropy, Voluntarism, and Grantmaking Foundations N.E.C.", "T99" ],

      # --- U: Science and Technology (NTEE) ---
      [ "U01 - Alliance/Advocacy", "U01" ],
      [ "U02 - Management & Technical Assistance", "U02" ],
      [ "U03 - Professional Societies, Associations", "U03" ],
      [ "U05 - Research Institutes and Public Policy Analysis", "U05" ],
      [ "U11 - Single Organization Support", "U11" ],
      [ "U12 - Fund Raising and Fund Distribution", "U12" ],
      [ "U19 - Support N.E.C.", "U19" ],
      [ "U20 - General Science", "U20" ],
      [ "U21 - Marine Science and Oceanography", "U21" ],
      [ "U30 - Physical & Earth Sciences", "U30" ],
      [ "U31 - Astronomy", "U31" ],
      [ "U33 - Chemistry, Chemical Engineering", "U33" ],
      [ "U34 - Mathematics", "U34" ],
      [ "U36 - Geology", "U36" ],
      [ "U40 - Engineering and Technology", "U40" ],
      [ "U41 - Computer Science", "U41" ],
      [ "U42 - Engineering", "U42" ],
      [ "U50 - Biological & Life Sciences", "U50" ],
      [ "U99 - Science and Technology N.E.C.", "U99" ],

      # --- V: Social Science (NTEE) ---
      [ "V01 - Alliance/Advocacy", "V01" ],
      [ "V02 - Management & Technical Assistance", "V02" ],
      [ "V03 - Professional Societies, Associations", "V03" ],
      [ "V05 - Research Institutes and Public Policy Analysis", "V05" ],
      [ "V11 - Single Organization Support", "V11" ],
      [ "V12 - Fund Raising and Fund Distribution", "V12" ],
      [ "V19 - Support N.E.C.", "V19" ],
      [ "V20 - Social Science", "V20" ],
      [ "V21 - Anthropology, Sociology", "V21" ],
      [ "V22 - Economics", "V22" ],
      [ "V23 - Behavioral Science", "V23" ],
      [ "V24 - Political Science", "V24" ],
      [ "V25 - Population Studies", "V25" ],
      [ "V26 - Law, Jurisprudence", "V26" ],
      [ "V30 - Interdisciplinary Research", "V30" ],
      [ "V31 - Black Studies", "V31" ],
      [ "V32 - Women's Studies", "V32" ],
      [ "V33 - Ethnic Studies", "V33" ],
      [ "V34 - Urban Studies", "V34" ],
      [ "V35 - International Studies", "V35" ],
      [ "V36 - Gerontology", "V36" ],
      [ "V37 - Labor Studies", "V37" ],
      [ "V99 - Social Science N.E.C.", "V99" ],

      # --- W: Public & Societal Benefit (NTEE) ---
      [ "W01 - Alliance/Advocacy", "W01" ],
      [ "W02 - Management & Technical Assistance", "W02" ],
      [ "W03 - Professional Societies, Associations", "W03" ],
      [ "W05 - Research Institutes and Public Policy Analysis", "W05" ],
      [ "W11 - Single Organization Support", "W11" ],
      [ "W12 - Fund Raising and Fund Distribution", "W12" ],
      [ "W19 - Support N.E.C.", "W19" ],
      [ "W20 - Government and Public Administration", "W20" ],
      [ "W22 - Public Finance, Taxation, Monetary Policy", "W22" ],
      [ "W24 - Citizen Participation", "W24" ],
      [ "W30 - Military, Veterans' Organizations", "W30" ],
      [ "W40 - Public Transportation Systems", "W40" ],
      [ "W50 - Telecommunications", "W50" ],
      [ "W60 - Financial Institutions", "W60" ],
      [ "W61 - Credit Unions", "W61" ],
      [ "W70 - Leadership Development", "W70" ],
      [ "W80 - Public Utilities", "W80" ],
      [ "W90 - Consumer Protection", "W90" ],
      [ "W99 - Public, Society Benefit N.E.C.", "W99" ],

      # --- X: Religion-Related (NTEE) ---
      [ "X01 - Alliance/Advocacy", "X01" ],
      [ "X02 - Management & Technical Assistance", "X02" ],
      [ "X03 - Professional Societies & Associations", "X03" ],
      [ "X05 - Research Institutes and Public Policy Analysis", "X05" ],
      [ "X11 - Single Organization Support", "X11" ],
      [ "X12 - Fund Raising and Fund Distribution", "X12" ],
      [ "X19 - Support N.E.C.", "X19" ],
      [ "X20 - Christianity", "X20" ],
      [ "X21 - Protestant", "X21" ],
      [ "X22 - Roman Catholic", "X22" ],
      [ "X30 - Judaism", "X30" ],
      [ "X40 - Islam", "X40" ],
      [ "X50 - Buddhism", "X50" ],
      [ "X70 - Hinduism", "X70" ],
      [ "X80 - Religious Media, Communications", "X80" ],
      [ "X81 - Religious Film, Video", "X81" ],
      [ "X82 - Religious Television", "X82" ],
      [ "X83 - Religious Printing, Publishing", "X83" ],
      [ "X84 - Religious Radio", "X84" ],
      [ "X90 - Interfaith Coalitions", "X90" ],
      [ "X99 - Religion Related N.E.C.", "X99" ],

      # --- Y: Mutual/Membership Benefit (NTEE) ---
      [ "Y01 - Alliance/Advocacy", "Y01" ],
      [ "Y02 - Management & Technical Assistance", "Y02" ],
      [ "Y03 - Professional Societies, Associations", "Y03" ],
      [ "Y05 - Research Institutes and Public Policy Analysis", "Y05" ],
      [ "Y11 - Single Organization Support", "Y11" ],
      [ "Y12 - Fund Raising and Fund Distribution", "Y12" ],
      [ "Y19 - Support N.E.C.", "Y19" ],
      [ "Y20 - Insurance Providers", "Y20" ],
      [ "Y22 - Local Benevolent Life Insurance Associations", "Y22" ],
      [ "Y23 - Mutual Insurance Company & Associations", "Y23" ],
      [ "Y24 - Supplemental Unemployment Compensation", "Y24" ],
      [ "Y25 - State-Sponsored Worker's Compensation Reinsurance Organizations", "Y25" ],
      [ "Y30 - Pension and Retirement Funds", "Y30" ],
      [ "Y33 - Teachers Retirement Fund Association", "Y33" ],
      [ "Y34 - Employee Funded Pension Trusts", "Y34" ],
      [ "Y35 - Multi-Employer Pension Plans", "Y35" ],
      [ "Y40 - Fraternal Societies", "Y40" ],
      [ "Y41 - Fraternal Beneficiary Societies", "Y41" ],
      [ "Y42 - Domestic Fraternal Societies", "Y42" ],
      [ "Y43 - Voluntary Employees Beneficiary Associations (Non-Government)", "Y43" ],
      [ "Y44 - Voluntary Employees Beneficiary Associations (Government)", "Y44" ],
      [ "Y50 - Cemeteries", "Y50" ],
      [ "Y99 - Mutual/Membership Benefit N.E.C.", "Y99" ],

      # --- Z: Unknown (NTEE) ---
      [ "Z99 - Unknown", "Z99" ]
    ]
    options_for_select(options, params[:ntee_filter])
  end

  def grant_status_tag(organization)
    # Priority 1: Actual grants found in the XML data (most reliable)
    if organization.has_grants_in_xml?
      status = "Grants Found (XML)"
      classes = "bg-purple-100 text-purple-800 font-medium"

    # Priority 2: CSV data indicates grants to individuals (strong indicator)
    elsif organization.grnt_indiv_cd == 'Y'
      status = "Individual Grants (CSV)"
      classes = "bg-green-100 text-green-800 font-medium"

    # Priority 3: XML flag indicates grants to individuals
    elsif organization.grants_to_individuals_ind == 'X'
      status = "Individual Grants (XML Flag)"
      classes = "bg-blue-100 text-blue-800 font-medium"

    # Default: No positive grant indicators found
    else
      status = "No Grants Indicated"
      classes = "bg-gray-100 text-gray-800"
    end

    tag.span status, class: "text-xs px-2 py-1 rounded-full #{classes}"
  end
end
